### ISSUE TITLE
.JSON Dictionary Rework

### ISSUE THREAD

**Issue by Dylan-SC** [SpencerWBarnes/PiMon#25]
The JavaScript in the client code should write null values to each dictionary key in the JSON Object initially.

When the JSON Object is parsed, and there is a value read for a specific key, the null value will be overwritten with the new corresponding value.

Once parsed, and the values have been updated as needed, the client will create a queue array for each dictionary instance in the JSON Object. The queue arrays will then append data from their corresponding dictionary at each cycle.

The queue arrays will then be interpreted by (or appended to) the correct data chart

**Comment by SpencerWBarnes** [comment]
I believe this issue has become stale and is no longer applicable.
